<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Informasi tentang organisasi anda digunakan untuk menghasilkan sertifikat keamanan dan standar perangkat lunak lainnya. ';
$lang['organization_app_name'] = 'Organisasi';
$lang['organization_city'] = 'Kota';
$lang['organization_city_invalid'] = 'Kota tidak benar.';
$lang['organization_country'] = 'Negara ';
$lang['organization_country_invalid'] = 'Negara tidak benar.';
$lang['organization_organization'] = 'Organisasi';
$lang['organization_organization_invalid'] = 'Organisasi tidak benar.';
$lang['organization_postal_code'] = 'Kode pos/Zip';
$lang['organization_postal_code_invalid'] = 'Kode pos tidak benar.';
$lang['organization_region'] = 'State, Province or Region';
$lang['organization_region_invalid'] = 'State, Province or Region is invalid.';
$lang['organization_street_address'] = 'Alamat jalan';
$lang['organization_street_address_invalid'] = 'Alamat tidak benar.';
$lang['organization_unit'] = 'Bagian';
$lang['organization_unit_invalid'] = 'Bagian tidak benar.';
