<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Informationen zu Ihrer Firma werden dazu verwendet Sicherheitszertifikate zu generieren und weitere Softwareeinstellungen zu setzen.';
$lang['organization_app_name'] = 'Firma';
$lang['organization_city'] = 'Stadt';
$lang['organization_city_invalid'] = 'Stadt ist ungültig.';
$lang['organization_country'] = 'Land';
$lang['organization_country_invalid'] = 'Land ist ungültig.';
$lang['organization_organization'] = 'Abteilung';
$lang['organization_organization_invalid'] = 'Abteilung ist ungültig.';
$lang['organization_postal_code'] = 'Postleitzahl';
$lang['organization_postal_code_invalid'] = 'Postleitzahl ist ungültig.';
$lang['organization_region'] = 'State, Province or Region';
$lang['organization_region_invalid'] = 'State, Province or Region is invalid.';
$lang['organization_street_address'] = 'Adresse';
$lang['organization_street_address_invalid'] = 'Adresse ist ungültig.';
$lang['organization_unit'] = 'Unterabteilung';
$lang['organization_unit_invalid'] = 'Unterabteilung ist ungültig.';
