<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Informações sobre sua organização é usado para gerar certificados de segurança e padrões de software.';
$lang['organization_app_name'] = 'Organização';
$lang['organization_city'] = 'Cidade';
$lang['organization_city_invalid'] = 'Cidade Inválida.';
$lang['organization_country'] = 'País';
$lang['organization_country_invalid'] = 'País Inválido';
$lang['organization_organization'] = 'Organização';
$lang['organization_organization_invalid'] = 'Organização Inválida.';
$lang['organization_postal_code'] = 'CEP';
$lang['organization_postal_code_invalid'] = 'CEP Inválido.';
$lang['organization_region'] = 'State, Province or Region';
$lang['organization_region_invalid'] = 'State, Province or Region is invalid.';
$lang['organization_street_address'] = 'Endereço';
$lang['organization_street_address_invalid'] = 'Endereço Inválido.';
$lang['organization_unit'] = 'Número';
$lang['organization_unit_invalid'] = 'Número Inválido.';
