<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'သင္႔အဖြဲ႔အစည္း၏ သတင္းအခ်က္အလက္သည္ လံုျခံဳေရးအေထာက္အထားျပဳလုပ္ရန္ႏွင္႔ အျခား software မ်ားအတြင္ အသံုးျပဳသည္။';
$lang['organization_app_name'] = 'အဖြဲ႔အစည္း';
$lang['organization_city'] = 'ျမိဳ႕ေတာ္';
$lang['organization_city_invalid'] = 'ျမိဳ႔ေတာ္ မွားယြင္းေနသည္။';
$lang['organization_country'] = 'ႏိုင္ငံ';
$lang['organization_country_invalid'] = 'ႏိုင္ငံမွားယြင္းေနသည္။';
$lang['organization_organization'] = 'အဖြဲ႔အစည္း';
$lang['organization_organization_invalid'] = 'အဖြဲ႔အစည္းမွားယြင္းေနသည္။';
$lang['organization_postal_code'] = 'စာတိုက္ေသတၱာအမွတ္';
$lang['organization_postal_code_invalid'] = 'စာတိုက္ေသတၱာအမွတ္မွားယြင္းေနသည္။';
$lang['organization_region'] = 'State, Province or Region';
$lang['organization_region_invalid'] = 'State, Province or Region is invalid.';
$lang['organization_street_address'] = 'လမ္းလိပ္စာ';
$lang['organization_street_address_invalid'] = 'လမ္းလိပ္စာမွားယြင္းေနသည္။';
$lang['organization_unit'] = 'ယူနစ္';
$lang['organization_unit_invalid'] = 'ယူနစ္မွားယြင္းေနသည္။';
