<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Informacje o Twojej organizacji są używane do wygenerowania certyfikatów bezpieczeństwa i wartości domyślnych do niektórych aplikacji.';
$lang['organization_app_name'] = 'Organizacja';
$lang['organization_city'] = 'Miasto';
$lang['organization_city_invalid'] = 'Podana nazwa miasta jest nieprawidłowa.';
$lang['organization_country'] = 'Kraj';
$lang['organization_country_invalid'] = 'Podana nazwa kraju jest nieprawidłowa.';
$lang['organization_organization'] = 'Organizacja';
$lang['organization_organization_invalid'] = 'Podana nazwa organizacji jest nieprawidłowa.';
$lang['organization_postal_code'] = 'Kod pocztowy';
$lang['organization_postal_code_invalid'] = 'Podany kod pocztowy jest nieprawidłowy.';
$lang['organization_region'] = 'State, Province or Region';
$lang['organization_region_invalid'] = 'State, Province or Region is invalid.';
$lang['organization_street_address'] = 'Ulica';
$lang['organization_street_address_invalid'] = 'Podana nazwa ulicy jest nieprawidłowa.';
$lang['organization_unit'] = 'Jednostka';
$lang['organization_unit_invalid'] = 'Podana nazwa jednostki jest nieprawidłowa.';
